#!/usr/bin/env python3
"""
LA PAGE « POURQUOI BLASTCLEAR », DANS LES TREIZE LANGUES.

─── POURQUOI UN MODULE À PART ──────────────────────────────────────────────────
Le convertisseur transforme des canevas ; cette page, elle, n'en vient d'aucun :
c'est du texte rédigé. Sept cents mots multipliés par treize langues n'ont rien à
faire au milieu d'un outil de conversion, et les mêler rendrait l'un et l'autre
illisibles.

─── CE QUE LA PAGE DIT, ET CE QU'ELLE NE DIT PAS ───────────────────────────────
Elle porte l'argumentaire technique : ce que le périmètre circulaire apporte, les
deux limites qui tiennent à sa forme même, et ce que le dôme balistique y répond.

Elle NE porte PAS les affirmations du brouillon qui ne peuvent pas être étayées :
conformité à un référentiel de grands barrages, « conformité garantie »,
« audit-proof », « zéro incompatibilité », tirs souterrains, courbe d'apprentissage
divisée par trois. Une page web est un document opposable, et une garantie de
conformité engage son auteur.

Le seul chiffre conservé est celui qui figure déjà sur l'accueil, avec la même
réserve qu'à cet endroit.
"""

# Structure d'une langue :
#   surtitre, titre, chapo,
#   sections : liste de (titre, [paragraphes], [éléments de liste])
#   note      : la réserve qui accompagne le chiffre
#   bouton    : libellé du bouton qui mène ici depuis l'accueil
#   appel     : libellé du bouton d'appel à l'action en fin de page

POURQUOI = {

'fr': {
 'surtitre': 'POURQUOI',
 'titre': 'Pourquoi BlastClear',
 'chapo': "Les équipes forage et sautage consacrent un temps considérable aux périmètres d'évacuation, de leur conception à leur diffusion. La plupart s'en tiennent au cercle. Voici ce que le cercle apporte, ce qu'il ne peut pas faire, et ce que le dôme balistique y change.",
 'sections': [
  ("Ce que le périmètre circulaire apporte",
   ["Centré sur le barycentre du tir, il est le minimum qu'un plan d'évacuation doit comporter. Il remplit trois fonctions."],
   ["Évaluer l'emprise des projections, à portée maximale, sur l'environnement du tir.",
    "Prévenir le personnel et les conducteurs d'engins, et protéger les installations fixes ou difficilement déplaçables.",
    "Éprouver l'effet des paramètres du tir, charge par délai et hauteur de bourrage, sur la portée des projections."]),
  ("Ses deux limites tiennent à sa forme",
   ["Elles ne viennent pas de la mise en œuvre : un cercle ne peut ni l'une ni l'autre.",
    "<b>Il ignore le relief.</b> Un rayon unique s'applique à une topographie qui, elle, ne l'est pas. Il est sous-estimé vers les points bas, où un projectile retombe plus loin, et sur-estimé vers les points hauts, où il retombe plus près. Le premier cas est un risque ; le second immobilise du terrain sans raison.",
    "<b>Il ignore le sens du tir.</b> Les projections ne partent pas également dans toutes les directions : le séquencement de mise à feu leur donne une direction dominante. Un rayon fixe traite donc l'arrière du tir comme l'avant, et retient partout la portée maximale."],
   []),
  ("Plusieurs tirs, un seul plan",
   ["La difficulté augmente quand plusieurs tirs voisins partent dans la même volée. Il faut calculer chaque périmètre, les fusionner en un tracé unique, et le faire à partir de fichiers venus de plusieurs logiciels avant d'obtenir le plan.",
    "Chaque reprise manuelle est une occasion d'erreur, sur une donnée qui commande l'évacuation de personnes."],
   []),
  ("Ce que le dôme balistique change",
   ["Il répond aux deux limites à la fois, et apporte quatre choses."],
   ["<b>Il est construit sur la géométrie réelle du tir.</b> Ce sont les trous extrêmes du contour qui le définissent, et non le seul barycentre.",
    "<b>Il est intersecté avec la topographie du site.</b> Le périmètre obtenu suit le terrain, ses banquettes et ses ruptures de pente, et non un plan horizontal théorique.",
    "<b>Il se module par secteur.</b> Chaque cadran reçoit son rayon selon l'orientation du tir, au lieu d'un rayon unique appliqué partout.",
    "<b>Il rend le résultat reproductible.</b> Les mêmes données et les mêmes réglages donnent le même périmètre, quelle que soit la personne qui le calcule."]),
  ("Ce que BlastClear en fait",
   ["BlastClear applique cette approche aux trois familles de tirs dans un seul environnement : contours fermés pour la production, polylignes pour le pré-découpage, points pour le pétardage et le tir de blocs. Les tirs d'une même volée se fondent en un périmètre unique, et le résultat sort en plan PDF, en DXF ou en image."],
   []),
 ],
 'note': "Sur une exploitation à ciel ouvert, le temps repris sur ces manipulations est estimé à environ deux cents heures par an. Les gains réels dépendent du contexte du site.",
 'bouton': 'En savoir plus',
 'appel': 'Demander une démo',
},

'en': {
 'surtitre': 'WHY',
 'titre': 'Why BlastClear',
 'chapo': "Drill and blast teams spend a great deal of time on clearance perimeters, from design through to distribution. Most stay with the circle. Here is what the circle gives you, what it cannot do, and what the ballistic dome changes.",
 'sections': [
  ("What the circular perimeter gives you",
   ["Centred on the blast's centroid, it is the minimum any clearance plan must carry. It serves three purposes."],
   ["Assess the reach of the throw, at maximum range, over the surroundings of the blast.",
    "Warn personnel and machine operators, and protect fixed or hard-to-move installations.",
    "Test the effect of the blast parameters, charge per delay and stemming height, on the reach of the throw."]),
  ("Its two limits come from its shape",
   ["They do not come from how it is applied: a circle can do neither.",
    "<b>It ignores the ground.</b> A single radius is applied to a topography that is anything but uniform. It is under-estimated towards low ground, where a fragment lands further out, and over-estimated towards high ground, where it lands closer in. The first is a risk; the second ties up ground for nothing.",
    "<b>It ignores the direction of the blast.</b> Throw is not equal in every direction: the firing sequence gives it a dominant one. A fixed radius therefore treats the back of the blast like the front, and holds the maximum range everywhere."],
   []),
  ("Several blasts, one plan",
   ["It gets harder when several neighbouring blasts go in the same round. Each perimeter has to be computed, then merged into a single outline, and all of it from files produced by several different programs before the drawing exists.",
    "Every manual step is an opportunity for error, on a figure that decides whether people are moved out of the way."],
   []),
  ("What the ballistic dome changes",
   ["It answers both limits at once, and brings four things."],
   ["<b>It is built on the real geometry of the blast.</b> The outermost holes of the outline define it, not the centroid alone.",
    "<b>It is intersected with the site topography.</b> The resulting perimeter follows the ground, its benches and its breaks of slope, rather than a theoretical horizontal plane.",
    "<b>It is graded by sector.</b> Each sector takes its own radius according to the blast direction, instead of one radius applied everywhere.",
    "<b>It makes the result repeatable.</b> The same data and the same settings give the same perimeter, whoever computes it."]),
  ("What BlastClear makes of it",
   ["BlastClear applies this approach to all three families of blast in a single environment: closed contours for production, polylines for pre-splitting, points for secondary and boulder blasting. Blasts of the same round merge into a single perimeter, and the result comes out as a PDF drawing, as DXF or as an image."],
   []),
 ],
 'note': "On one open-pit operation, the time recovered from this handling is estimated at around two hundred hours a year. Actual gains depend on site context.",
 'bouton': 'Read more',
 'appel': 'Request a demo',
},

'es': {
 'surtitre': 'POR QUÉ',
 'titre': 'Por qué BlastClear',
 'chapo': "Los equipos de perforación y voladura dedican mucho tiempo a los perímetros de evacuación, desde su diseño hasta su difusión. La mayoría se queda con el círculo. Esto es lo que el círculo aporta, lo que no puede hacer, y lo que la cúpula balística cambia.",
 'sections': [
  ("Lo que aporta el perímetro circular",
   ["Centrado en el baricentro de la voladura, es el mínimo que todo plan de evacuación debe contener. Cumple tres funciones."],
   ["Evaluar el alcance de las proyecciones, a distancia máxima, sobre el entorno de la voladura.",
    "Advertir al personal y a los operadores de equipos, y proteger las instalaciones fijas o difíciles de desplazar.",
    "Comprobar el efecto de los parámetros de la voladura, carga por retardo y altura del taco, sobre el alcance de las proyecciones."]),
  ("Sus dos límites vienen de su forma",
   ["No vienen de cómo se aplica: un círculo no puede ni lo uno ni lo otro.",
    "<b>Ignora el relieve.</b> Un radio único se aplica a una topografía que no lo es. Queda subestimado hacia las cotas bajas, donde un proyectil cae más lejos, y sobreestimado hacia las cotas altas, donde cae más cerca. El primer caso es un riesgo; el segundo inmoviliza terreno sin motivo.",
    "<b>Ignora el sentido de la voladura.</b> Las proyecciones no salen por igual en todas las direcciones: la secuencia de encendido les da una dirección dominante. Un radio fijo trata entonces la parte trasera como la delantera, y mantiene en todas partes el alcance máximo."],
   []),
  ("Varias voladuras, un solo plano",
   ["La dificultad aumenta cuando varias voladuras vecinas se disparan en la misma pega. Hay que calcular cada perímetro, fusionarlos en un solo trazado, y hacerlo a partir de archivos procedentes de varios programas antes de obtener el plano.",
    "Cada retoque manual es una ocasión de error, sobre un dato que decide la evacuación de personas."],
   []),
  ("Lo que cambia la cúpula balística",
   ["Responde a los dos límites a la vez, y aporta cuatro cosas."],
   ["<b>Se construye sobre la geometría real de la voladura.</b> La definen los barrenos extremos del contorno, y no el baricentro solo.",
    "<b>Se interseca con la topografía del emplazamiento.</b> El perímetro obtenido sigue el terreno, sus bancos y sus quiebres de pendiente, y no un plano horizontal teórico.",
    "<b>Se gradúa por sectores.</b> Cada sector recibe su radio según la orientación de la voladura, en lugar de un radio único aplicado en todas partes.",
    "<b>Hace el resultado reproducible.</b> Los mismos datos y los mismos ajustes dan el mismo perímetro, sea quien sea quien lo calcule."]),
  ("Lo que BlastClear hace con ello",
   ["BlastClear aplica este enfoque a las tres familias de voladura en un solo entorno: contornos cerrados para producción, polilíneas para precorte, puntos para voladura secundaria y de bolones. Las voladuras de una misma pega se funden en un perímetro único, y el resultado sale en plano PDF, en DXF o en imagen."],
   []),
 ],
 'note': "En una explotación a cielo abierto, el tiempo recuperado de estas manipulaciones se estima en unas doscientas horas al año. Los beneficios reales dependen del contexto del emplazamiento.",
 'bouton': 'Saber más',
 'appel': 'Solicitar una demo',
},

'pt': {
 'surtitre': 'PORQUÊ',
 'titre': 'Porquê o BlastClear',
 'chapo': "As equipas de perfuração e desmonte dedicam muito tempo aos perímetros de evacuação, da conceção à difusão. A maioria fica-se pelo círculo. Eis o que o círculo traz, o que não consegue fazer, e o que a cúpula balística muda.",
 'sections': [
  ("O que traz o perímetro circular",
   ["Centrado no baricentro do fogo, é o mínimo que qualquer plano de evacuação deve conter. Cumpre três funções."],
   ["Avaliar o alcance das projeções, à distância máxima, sobre a envolvente do fogo.",
    "Avisar o pessoal e os operadores de equipamentos, e proteger as instalações fixas ou de difícil deslocação.",
    "Testar o efeito dos parâmetros do fogo, carga por retardo e altura do atacamento, sobre o alcance das projeções."]),
  ("Os seus dois limites vêm da sua forma",
   ["Não vêm da forma como é aplicado: um círculo não consegue nem uma coisa nem outra.",
    "<b>Ignora o relevo.</b> Um raio único aplica-se a uma topografia que não o é. Fica subestimado para as cotas baixas, onde um projétil cai mais longe, e sobrestimado para as cotas altas, onde cai mais perto. O primeiro caso é um risco; o segundo imobiliza terreno sem motivo.",
    "<b>Ignora o sentido do fogo.</b> As projeções não saem igualmente em todas as direções: a sequência de iniciação dá-lhes uma direção dominante. Um raio fixo trata então a retaguarda como a frente, e mantém em todo o lado o alcance máximo."],
   []),
  ("Vários fogos, um só desenho",
   ["A dificuldade aumenta quando vários fogos vizinhos são detonados na mesma pega. É preciso calcular cada perímetro, fundi-los num traçado único, e fazê-lo a partir de ficheiros vindos de vários programas antes de obter o desenho.",
    "Cada retoque manual é uma ocasião de erro, sobre um dado que decide a evacuação de pessoas."],
   []),
  ("O que muda a cúpula balística",
   ["Responde aos dois limites ao mesmo tempo, e traz quatro coisas."],
   ["<b>É construída sobre a geometria real do fogo.</b> São os furos extremos do contorno que a definem, e não apenas o baricentro.",
    "<b>É intersetada com a topografia do local.</b> O perímetro obtido acompanha o terreno, as suas bancadas e as suas quebras de declive, e não um plano horizontal teórico.",
    "<b>É graduada por setores.</b> Cada setor recebe o seu raio consoante a orientação do fogo, em vez de um raio único aplicado em todo o lado.",
    "<b>Torna o resultado reproduzível.</b> Os mesmos dados e as mesmas definições dão o mesmo perímetro, seja quem for que o calcule."]),
  ("O que o BlastClear faz com isso",
   ["O BlastClear aplica esta abordagem às três famílias de fogo num só ambiente: contornos fechados para produção, polilinhas para pré-corte, pontos para fogo secundário e desmonte de matacões. Os fogos da mesma pega fundem-se num perímetro único, e o resultado sai em desenho PDF, em DXF ou em imagem."],
   []),
 ],
 'note': "Numa exploração a céu aberto, o tempo recuperado destas manipulações estima-se em cerca de duzentas horas por ano. Os ganhos reais dependem do contexto do local.",
 'bouton': 'Saber mais',
 'appel': 'Solicitar uma demo',
},

'it': {
 'surtitre': 'PERCHÉ',
 'titre': 'Perché BlastClear',
 'chapo': "Le squadre di perforazione e volata dedicano molto tempo ai perimetri di evacuazione, dalla progettazione alla diffusione. La maggior parte si ferma al cerchio. Ecco che cosa offre il cerchio, che cosa non può fare, e che cosa cambia la cupola balistica.",
 'sections': [
  ("Che cosa offre il perimetro circolare",
   ["Centrato sul baricentro della volata, è il minimo che ogni piano di evacuazione deve contenere. Assolve tre funzioni."],
   ["Valutare l'estensione delle proiezioni, alla portata massima, sull'intorno della volata.",
    "Avvertire il personale e gli operatori dei mezzi, e proteggere gli impianti fissi o difficilmente spostabili.",
    "Verificare l'effetto dei parametri della volata, carica per ritardo e altezza del borraggio, sulla portata delle proiezioni."]),
  ("I suoi due limiti derivano dalla sua forma",
   ["Non derivano da come viene applicato: un cerchio non può né l'uno né l'altro.",
    "<b>Ignora il rilievo.</b> Un raggio unico si applica a una topografia che non lo è. Risulta sottostimato verso le quote basse, dove un proietto ricade più lontano, e sovrastimato verso le quote alte, dove ricade più vicino. Il primo caso è un rischio; il secondo immobilizza terreno senza motivo.",
    "<b>Ignora il verso della volata.</b> Le proiezioni non partono ugualmente in tutte le direzioni: la sequenza di innesco dà loro una direzione dominante. Un raggio fisso tratta quindi il retro come il fronte, e mantiene ovunque la portata massima."],
   []),
  ("Più volate, un solo disegno",
   ["La difficoltà aumenta quando più volate vicine partono nella stessa serie. Occorre calcolare ogni perimetro, fonderli in un tracciato unico, e farlo a partire da file provenienti da più programmi prima di ottenere il disegno.",
    "Ogni ritocco manuale è un'occasione di errore, su un dato che decide l'evacuazione di persone."],
   []),
  ("Che cosa cambia la cupola balistica",
   ["Risponde a entrambi i limiti insieme, e porta quattro cose."],
   ["<b>È costruita sulla geometria reale della volata.</b> La definiscono i fori estremi del contorno, e non il solo baricentro.",
    "<b>È intersecata con la topografia del sito.</b> Il perimetro ottenuto segue il terreno, le sue gradonature e le sue rotture di pendenza, e non un piano orizzontale teorico.",
    "<b>È graduata per settori.</b> Ogni settore riceve il proprio raggio secondo l'orientamento della volata, invece di un raggio unico applicato ovunque.",
    "<b>Rende il risultato riproducibile.</b> Gli stessi dati e le stesse impostazioni danno lo stesso perimetro, chiunque lo calcoli."]),
  ("Che cosa ne fa BlastClear",
   ["BlastClear applica questo approccio alle tre famiglie di volata in un solo ambiente: contorni chiusi per la produzione, polilinee per il pretaglio, punti per il brillamento secondario e di blocchi. Le volate della stessa serie si fondono in un perimetro unico, e il risultato esce come disegno PDF, come DXF o come immagine."],
   []),
 ],
 'note': "Su una coltivazione a cielo aperto, il tempo recuperato da queste manipolazioni è stimato in circa duecento ore l'anno. I guadagni effettivi dipendono dal contesto del sito.",
 'bouton': 'Saperne di più',
 'appel': 'Richiedi una demo',
},

'de': {
 'surtitre': 'WARUM',
 'titre': 'Warum BlastClear',
 'chapo': "Bohr- und Sprengteams wenden viel Zeit für Evakuierungsperimeter auf, von der Planung bis zur Verteilung. Die meisten bleiben beim Kreis. Hier steht, was der Kreis leistet, was er nicht kann, und was die ballistische Kuppel daran ändert.",
 'sections': [
  ("Was der kreisförmige Perimeter leistet",
   ["Auf den Schwerpunkt der Sprengung zentriert, ist er das Mindeste, was jeder Evakuierungsplan enthalten muss. Er erfüllt drei Aufgaben."],
   ["Die Reichweite des Wurfs bei maximaler Weite auf das Umfeld der Sprengung beurteilen.",
    "Personal und Gerätefahrer warnen sowie feste oder schwer versetzbare Anlagen schützen.",
    "Die Wirkung der Sprengparameter, Lademenge je Zündstufe und Besatzhöhe, auf die Wurfweite prüfen."]),
  ("Seine zwei Grenzen liegen in seiner Form",
   ["Sie liegen nicht an der Anwendung: ein Kreis kann weder das eine noch das andere.",
    "<b>Er ignoriert das Gelände.</b> Ein einziger Radius wird auf eine Geländeoberfläche angewandt, die keineswegs eben ist. Er ist zu tiefliegenden Bereichen hin unterschätzt, wo ein Wurfstück weiter fliegt, und zu hochliegenden hin überschätzt, wo es näher niedergeht. Der erste Fall ist ein Risiko; der zweite legt Gelände ohne Grund still.",
    "<b>Er ignoriert die Sprengrichtung.</b> Der Wurf verteilt sich nicht gleichmäßig: die Zündfolge gibt ihm eine Vorzugsrichtung. Ein fester Radius behandelt die Rückseite daher wie die Front und hält überall die maximale Weite."],
   []),
  ("Mehrere Sprengungen, ein Plan",
   ["Schwieriger wird es, wenn mehrere benachbarte Sprengungen im selben Abschlag gehen. Jeder Perimeter muss berechnet, alle zu einem Umriss verschmolzen werden, und das aus Dateien mehrerer Programme, bevor der Plan überhaupt vorliegt.",
    "Jeder Handgriff ist eine Fehlerquelle, bei einer Angabe, die über die Räumung von Menschen entscheidet."],
   []),
  ("Was die ballistische Kuppel ändert",
   ["Sie beantwortet beide Grenzen zugleich und bringt vier Dinge."],
   ["<b>Sie wird auf der wirklichen Geometrie der Sprengung aufgebaut.</b> Die äußersten Bohrlöcher der Kontur bestimmen sie, nicht der Schwerpunkt allein.",
    "<b>Sie wird mit der Geländeoberfläche verschnitten.</b> Der entstehende Perimeter folgt dem Gelände, seinen Bermen und Geländekanten, und nicht einer theoretischen Horizontalebene.",
    "<b>Sie wird sektorweise abgestuft.</b> Jeder Sektor erhält seinen eigenen Radius je nach Sprengrichtung, statt eines überall gleichen Radius.",
    "<b>Sie macht das Ergebnis wiederholbar.</b> Dieselben Daten und dieselben Einstellungen ergeben denselben Perimeter, gleich wer ihn berechnet."]),
  ("Was BlastClear daraus macht",
   ["BlastClear wendet diesen Ansatz auf alle drei Sprengungsarten in einer einzigen Umgebung an: geschlossene Konturen für die Produktion, Polylinien für die Vorspaltsprengung, Punkte für Nachsprengung und Knäppern. Sprengungen desselben Abschlags verschmelzen zu einem Perimeter, und das Ergebnis liegt als PDF-Plan, als DXF oder als Bild vor."],
   []),
 ],
 'note': "In einem Tagebaubetrieb wird die bei diesen Arbeitsschritten gewonnene Zeit auf etwa zweihundert Stunden im Jahr geschätzt. Die tatsächlichen Einsparungen hängen vom Standort ab.",
 'bouton': 'Mehr erfahren',
 'appel': 'Demo anfragen',
},

'nl': {
 'surtitre': 'WAAROM',
 'titre': 'Waarom BlastClear',
 'chapo': "Boor- en schietploegen besteden veel tijd aan evacuatieperimeters, van ontwerp tot verspreiding. De meesten blijven bij de cirkel. Dit is wat de cirkel oplevert, wat hij niet kan, en wat de ballistische koepel daaraan verandert.",
 'sections': [
  ("Wat de cirkelvormige perimeter oplevert",
   ["Gecentreerd op het zwaartepunt van het schot is hij het minimum dat elk evacuatieplan moet bevatten. Hij vervult drie functies."],
   ["De reikwijdte van de worp op maximale afstand op de omgeving van het schot beoordelen.",
    "Personeel en machinisten waarschuwen, en vaste of moeilijk verplaatsbare installaties beschermen.",
    "Het effect van de schotparameters, lading per vertraging en afdichtingshoogte, op de worpafstand toetsen."]),
  ("De twee grenzen liggen in zijn vorm",
   ["Ze liggen niet aan de toepassing: een cirkel kan het een noch het ander.",
    "<b>Hij negeert het reliëf.</b> Eén enkele straal wordt toegepast op een topografie die dat niet is. Hij is onderschat richting lage delen, waar een worpstuk verder valt, en overschat richting hoge delen, waar het dichterbij valt. Het eerste is een risico; het tweede legt terrein zonder reden stil.",
    "<b>Hij negeert de richting van het schot.</b> De worp gaat niet gelijk alle kanten op: de ontstekingsvolgorde geeft hem een overheersende richting. Een vaste straal behandelt de achterkant dus als de voorkant, en houdt overal de maximale afstand aan."],
   []),
  ("Meerdere schoten, één tekening",
   ["Het wordt lastiger wanneer meerdere naburige schoten in dezelfde ronde afgaan. Elke perimeter moet berekend worden, alle samengevoegd tot één omtrek, en dat uit bestanden van meerdere programma's voordat de tekening er is.",
    "Elke handmatige stap is een kans op fouten, bij een gegeven dat bepaalt of mensen worden weggehaald."],
   []),
  ("Wat de ballistische koepel verandert",
   ["Hij beantwoordt beide grenzen tegelijk, en brengt vier dingen."],
   ["<b>Hij wordt op de werkelijke geometrie van het schot gebouwd.</b> De buitenste boorgaten van de contour bepalen hem, niet alleen het zwaartepunt.",
    "<b>Hij wordt doorsneden met de topografie van de locatie.</b> De verkregen perimeter volgt het terrein, de bermen en de hellingbreuken, en niet een theoretisch horizontaal vlak.",
    "<b>Hij wordt per sector gegradeerd.</b> Elke sector krijgt zijn eigen straal naar gelang de schotrichting, in plaats van één straal overal.",
    "<b>Hij maakt het resultaat herhaalbaar.</b> Dezelfde gegevens en dezelfde instellingen geven dezelfde perimeter, wie hem ook berekent."]),
  ("Wat BlastClear ermee doet",
   ["BlastClear past deze aanpak toe op de drie soorten schoten in één omgeving: gesloten contouren voor productie, polylijnen voor voorsplijten, punten voor nasprengen en blokken sprengen. Schoten van dezelfde ronde smelten samen tot één perimeter, en het resultaat komt eruit als PDF-tekening, als DXF of als afbeelding."],
   []),
 ],
 'note': "Op één dagbouwmijn wordt de met deze handelingen gewonnen tijd geschat op ongeveer tweehonderd uur per jaar. De werkelijke winst hangt af van de situatie ter plaatse.",
 'bouton': 'Meer weten',
 'appel': 'Demo aanvragen',
},

'sv': {
 'surtitre': 'VARFÖR',
 'titre': 'Varför BlastClear',
 'chapo': "Borr- och sprängpersonal lägger mycket tid på utrymningsperimetrar, från projektering till spridning. De flesta stannar vid cirkeln. Här står vad cirkeln ger, vad den inte klarar, och vad den ballistiska kupolen ändrar på.",
 'sections': [
  ("Vad den cirkulära perimetern ger",
   ["Centrerad på salvans tyngdpunkt är den det minsta varje utrymningsplan måste innehålla. Den fyller tre syften."],
   ["Bedöma kastets räckvidd, vid maximal längd, på salvans omgivning.",
    "Varna personal och maskinförare, och skydda fasta eller svårflyttade anläggningar.",
    "Pröva hur salvans parametrar, laddning per intervall och förladdningshöjd, påverkar kastlängden."]),
  ("Dess två gränser ligger i formen",
   ["De beror inte på tillämpningen: en cirkel klarar varken det ena eller det andra.",
    "<b>Den bortser från terrängen.</b> En enda radie tillämpas på en topografi som inte är plan. Den underskattas mot lägre partier, där ett kaststycke når längre, och överskattas mot högre partier, där det landar närmare. Det första är en risk; det andra binder mark utan skäl.",
    "<b>Den bortser från salvans riktning.</b> Kastet går inte lika åt alla håll: tändföljden ger det en dominerande riktning. En fast radie behandlar därför baksidan som fronten, och håller överallt den längsta räckvidden."],
   []),
  ("Flera salvor, en enda ritning",
   ["Det blir svårare när flera närliggande salvor går i samma runda. Varje perimeter måste beräknas, alla slås samman till en enda kontur, och detta utifrån filer från flera program innan ritningen finns.",
    "Varje manuellt steg är ett tillfälle för fel, på en uppgift som avgör om människor flyttas undan."],
   []),
  ("Vad den ballistiska kupolen ändrar",
   ["Den möter båda gränserna på en gång, och ger fyra saker."],
   ["<b>Den byggs på salvans verkliga geometri.</b> Det är konturens yttersta hål som bestämmer den, inte tyngdpunkten ensam.",
    "<b>Den skärs mot platsens topografi.</b> Den perimeter som uppstår följer terrängen, dess pallar och lutningsbrott, och inte ett teoretiskt horisontalplan.",
    "<b>Den graderas sektorvis.</b> Varje sektor får sin egen radie efter salvans riktning, i stället för en och samma radie överallt.",
    "<b>Den gör resultatet upprepbart.</b> Samma data och samma inställningar ger samma perimeter, oavsett vem som räknar."]),
  ("Vad BlastClear gör av det",
   ["BlastClear tillämpar detta på alla tre typer av salvor i en enda miljö: slutna konturer för produktion, polylinjer för förspräckning, punkter för skutknackning och blocksprängning. Salvor i samma runda slås samman till en enda perimeter, och resultatet levereras som PDF-ritning, som DXF eller som bild."],
   []),
 ],
 'note': "På ett dagbrott uppskattas den tid som återvinns från detta arbete till omkring tvåhundra timmar om året. De faktiska vinsterna beror på förhållandena på platsen.",
 'bouton': 'Läs mer',
 'appel': 'Boka en demo',
},

'no': {
 'surtitre': 'HVORFOR',
 'titre': 'Hvorfor BlastClear',
 'chapo': "Bore- og sprengningslag bruker mye tid på evakueringsperimetre, fra prosjektering til formidling. De fleste blir ved sirkelen. Her står hva sirkelen gir, hva den ikke klarer, og hva den ballistiske kuppelen endrer.",
 'sections': [
  ("Hva den sirkulære perimeteren gir",
   ["Sentrert på salvens tyngdepunkt er den det minste enhver evakueringsplan må inneholde. Den fyller tre formål."],
   ["Vurdere kastets rekkevidde, på lengste avstand, på salvens omgivelser.",
    "Varsle personell og maskinførere, og verne faste eller vanskelig flyttbare anlegg.",
    "Prøve hvordan salvens parametre, ladning per intervall og fordemmingshøyde, påvirker kastlengden."]),
  ("De to grensene ligger i formen",
   ["De skyldes ikke bruken: en sirkel klarer verken det ene eller det andre.",
    "<b>Den ser bort fra terrenget.</b> Én enkelt radius brukes på en topografi som ikke er flat. Den undervurderes mot lavere partier, der et kaststykke når lenger, og overvurderes mot høyere partier, der det lander nærmere. Det første er en risiko; det andre binder areal uten grunn.",
    "<b>Den ser bort fra salvens retning.</b> Kastet går ikke likt i alle retninger: tennfølgen gir det en dominerende retning. En fast radius behandler derfor baksiden som fronten, og holder overalt den lengste rekkevidden."],
   []),
  ("Flere salver, én tegning",
   ["Det blir vanskeligere når flere nærliggende salver går i samme runde. Hver perimeter må beregnes, alle slås sammen til én kontur, og dette ut fra filer fra flere programmer før tegningen finnes.",
    "Hvert manuelt trinn er en mulighet for feil, på en opplysning som avgjør om mennesker flyttes unna."],
   []),
  ("Hva den ballistiske kuppelen endrer",
   ["Den svarer på begge grensene samtidig, og gir fire ting."],
   ["<b>Den bygges på salvens virkelige geometri.</b> Det er konturens ytterste hull som bestemmer den, ikke tyngdepunktet alene.",
    "<b>Den skjæres mot stedets topografi.</b> Perimeteren som oppstår følger terrenget, pallene og hellingsbruddene, og ikke et teoretisk horisontalplan.",
    "<b>Den graderes sektorvis.</b> Hver sektor får sin egen radius etter salvens retning, i stedet for én radius overalt.",
    "<b>Den gjør resultatet gjentakbart.</b> Samme data og samme innstillinger gir samme perimeter, uansett hvem som regner."]),
  ("Hva BlastClear gjør av det",
   ["BlastClear bruker denne tilnærmingen på alle tre salvetyper i ett og samme miljø: lukkede konturer for produksjon, polylinjer for forspalting, punkter for etterskyting og blokksprengning. Salver i samme runde slås sammen til én perimeter, og resultatet leveres som PDF-tegning, som DXF eller som bilde."],
   []),
 ],
 'note': "På ett dagbrudd anslås tiden som vinnes på dette arbeidet til rundt to hundre timer i året. Faktiske gevinster avhenger av forholdene på stedet.",
 'bouton': 'Les mer',
 'appel': 'Be om en demo',
},

'da': {
 'surtitre': 'HVORFOR',
 'titre': 'Hvorfor BlastClear',
 'chapo': "Bore- og sprængningshold bruger meget tid på evakueringsperimetre, fra projektering til udbredelse. De fleste bliver ved cirklen. Her står, hvad cirklen giver, hvad den ikke kan, og hvad den ballistiske kuppel ændrer.",
 'sections': [
  ("Hvad den cirkulære perimeter giver",
   ["Centreret om sprængningens tyngdepunkt er den det mindste, enhver evakueringsplan skal indeholde. Den opfylder tre formål."],
   ["Vurdere kastets rækkevidde, på største afstand, på sprængningens omgivelser.",
    "Advare personale og maskinførere, og beskytte faste eller vanskeligt flytbare anlæg.",
    "Afprøve, hvordan sprængningens parametre, ladning pr. interval og forladningshøjde, påvirker kastelængden."]),
  ("De to grænser ligger i formen",
   ["De skyldes ikke anvendelsen: en cirkel kan hverken det ene eller det andet.",
    "<b>Den ser bort fra terrænet.</b> Én enkelt radius anvendes på en topografi, der ikke er flad. Den undervurderes mod lavere partier, hvor et kaststykke når længere, og overvurderes mod højere partier, hvor det lander tættere på. Det første er en risiko; det andet binder areal uden grund.",
    "<b>Den ser bort fra sprængningens retning.</b> Kastet går ikke lige til alle sider: tændfølgen giver det en dominerende retning. En fast radius behandler derfor bagsiden som fronten og holder overalt den længste rækkevidde."],
   []),
  ("Flere sprængninger, én tegning",
   ["Det bliver sværere, når flere nærliggende sprængninger går i samme runde. Hver perimeter skal beregnes, alle lægges sammen til én kontur, og det ud fra filer fra flere programmer, før tegningen findes.",
    "Hvert manuelt trin er en anledning til fejl, på en oplysning der afgør, om mennesker flyttes væk."],
   []),
  ("Hvad den ballistiske kuppel ændrer",
   ["Den svarer på begge grænser på én gang og giver fire ting."],
   ["<b>Den bygges på sprængningens virkelige geometri.</b> Det er konturens yderste huller, der bestemmer den, ikke tyngdepunktet alene.",
    "<b>Den skæres mod stedets topografi.</b> Den perimeter, der opstår, følger terrænet, dets bænke og hældningsbrud, og ikke et teoretisk vandret plan.",
    "<b>Den gradueres sektorvis.</b> Hver sektor får sin egen radius efter sprængningens retning i stedet for én radius overalt.",
    "<b>Den gør resultatet gentageligt.</b> Samme data og samme indstillinger giver samme perimeter, uanset hvem der regner."]),
  ("Hvad BlastClear gør ved det",
   ["BlastClear anvender denne tilgang på alle tre sprængningstyper i ét og samme miljø: lukkede konturer til produktion, polylinjer til forspaltning, punkter til efterskydning og bloksprængning. Sprængninger i samme runde lægges sammen til én perimeter, og resultatet leveres som PDF-tegning, som DXF eller som billede."],
   []),
 ],
 'note': "På ét åbent brud anslås den tid, der vindes ved dette arbejde, til omkring to hundrede timer om året. De faktiske gevinster afhænger af forholdene på stedet.",
 'bouton': 'Læs mere',
 'appel': 'Bed om en demo',
},

'af': {
 'surtitre': 'WAAROM',
 'titre': 'Waarom BlastClear',
 'chapo': "Boor- en skietspanne bestee baie tyd aan ontruimingsomtrekke, van ontwerp tot verspreiding. Die meeste bly by die sirkel. Hier is wat die sirkel bied, wat dit nie kan doen nie, en wat die ballistiese koepel daaraan verander.",
 'sections': [
  ("Wat die sirkelvormige omtrek bied",
   ["Gesentreer op die skoot se swaartepunt is dit die minimum wat enige ontruimingsplan moet bevat. Dit vervul drie doele."],
   ["Die werp se bereik, op maksimum afstand, op die skoot se omgewing beoordeel.",
    "Personeel en masjienbestuurders waarsku, en vaste of moeilik verskuifbare installasies beskerm.",
    "Toets hoe die skoot se parameters, lading per vertraging en stophoogte, die werpafstand beïnvloed."]),
  ("Sy twee grense lê in sy vorm",
   ["Hulle kom nie van die toepassing nie: 'n sirkel kan nie die een of die ander nie.",
    "<b>Dit ignoreer die terrein.</b> Een enkele radius word toegepas op 'n topografie wat nie plat is nie. Dit word onderskat na laer dele, waar 'n werpstuk verder val, en oorskat na hoër dele, waar dit nader val. Die eerste is 'n risiko; die tweede bind grond sonder rede.",
    "<b>Dit ignoreer die skoot se rigting.</b> Die werp gaan nie ewe ver in alle rigtings nie: die ontstekingsvolgorde gee dit 'n oorheersende rigting. 'n Vaste radius behandel dus die agterkant soos die voorkant, en hou oral die grootste afstand."],
   []),
  ("Verskeie skote, een tekening",
   ["Dit raak moeiliker wanneer verskeie naburige skote in dieselfde ronde afgaan. Elke omtrek moet bereken word, almal saamgevoeg tot een kontoer, en dit uit lêers van verskeie programme voordat die tekening bestaan.",
    "Elke handmatige stap is 'n geleentheid vir foute, op 'n gegewe wat bepaal of mense weggeneem word."],
   []),
  ("Wat die ballistiese koepel verander",
   ["Dit beantwoord albei grense tegelyk, en bring vier dinge."],
   ["<b>Dit word op die skoot se werklike meetkunde gebou.</b> Die kontoer se buitenste gate bepaal dit, nie die swaartepunt alleen nie.",
    "<b>Dit word met die terrein se topografie gesny.</b> Die omtrek wat ontstaan, volg die terrein, sy banke en hellingbreuke, en nie 'n teoretiese horisontale vlak nie.",
    "<b>Dit word sektorsgewys gegradeer.</b> Elke sektor kry sy eie radius volgens die skoot se rigting, in plaas van een radius oral.",
    "<b>Dit maak die resultaat herhaalbaar.</b> Dieselfde data en dieselfde instellings gee dieselfde omtrek, wie dit ook al bereken."]),
  ("Wat BlastClear daarmee doen",
   ["BlastClear pas hierdie benadering toe op al drie soorte skote in een omgewing: geslote kontoere vir produksie, pollyne vir voorsplyting, punte vir nasketing en bloksketing. Skote van dieselfde ronde smelt saam tot een omtrek, en die resultaat kom uit as PDF-tekening, as DXF of as beeld."],
   []),
 ],
 'note': "By een oopgroefmyn word die tyd wat met hierdie werk gewen word, op ongeveer tweehonderd uur per jaar geraam. Werklike winste hang af van die terrein se omstandighede.",
 'bouton': 'Lees meer',
 'appel': "Versoek 'n demo",
},

'tr': {
 'surtitre': 'NEDEN',
 'titre': 'Neden BlastClear',
 'chapo': "Delme ve patlatma ekipleri tahliye çevrelerine, tasarımdan duyuruya kadar, çok zaman ayırır. Çoğu daireyle yetinir. İşte dairenin sağladığı, sağlayamadığı ve balistik kubbenin değiştirdiği şeyler.",
 'sections': [
  ("Dairesel çevrenin sağladığı",
   ["Atımın ağırlık merkezine oturtulan daire, her tahliye planının taşıması gereken asgari unsurdur. Üç işlevi vardır."],
   ["Savrulmanın azami menzilde atım çevresine etkisini değerlendirmek.",
    "Personeli ve makine operatörlerini uyarmak, sabit ya da güç taşınan tesisleri korumak.",
    "Atım parametrelerinin, gecikme başına şarj ve sıkılama yüksekliğinin, savrulma menziline etkisini sınamak."]),
  ("İki sınırı biçiminden gelir",
   ["Uygulanışından değil: bir daire ne birini ne ötekini yapabilir.",
    "<b>Araziyi göz ardı eder.</b> Tek bir yarıçap, düz olmayan bir topografyaya uygulanır. Alçak kesimlere doğru olduğundan küçük kalır; parça oralarda daha uzağa düşer. Yüksek kesimlere doğru ise olduğundan büyük kalır; parça oralarda daha yakına düşer. Birincisi risktir, ikincisi sebepsiz yere arazi bağlar.",
    "<b>Atımın yönünü göz ardı eder.</b> Savrulma her yöne eşit gitmez: ateşleme sırası ona baskın bir yön verir. Sabit bir yarıçap bu yüzden arkayı önle bir tutar ve her yerde azami menzili esas alır."],
   []),
  ("Birden çok atım, tek bir plan",
   ["Komşu birkaç atım aynı seride ateşlendiğinde iş zorlaşır. Her çevrenin hesaplanması, hepsinin tek bir hatta birleştirilmesi ve bunun birkaç ayrı programdan gelen dosyalarla yapılması gerekir.",
    "Elle yapılan her adım, insanların tahliyesine karar veren bir veride hata fırsatıdır."],
   []),
  ("Balistik kubbenin değiştirdiği",
   ["İki sınırı birden karşılar ve dört şey getirir."],
   ["<b>Atımın gerçek geometrisi üzerine kurulur.</b> Onu konturun en dıştaki delikleri belirler, yalnızca ağırlık merkezi değil.",
    "<b>Sahanın topografyasıyla kesiştirilir.</b> Elde edilen çevre araziyi, basamaklarını ve eğim kırıklıklarını izler; teorik bir yatay düzlemi değil.",
    "<b>Sektör sektör ayarlanır.</b> Her sektör, atımın yönüne göre kendi yarıçapını alır; her yere aynı yarıçap uygulanmaz.",
    "<b>Sonucu yinelenebilir kılar.</b> Aynı veri ve aynı ayarlar, kim hesaplarsa hesaplasın aynı çevreyi verir."]),
  ("BlastClear bundan ne çıkarır",
   ["BlastClear bu yaklaşımı üç atım ailesine tek bir ortamda uygular: üretim için kapalı konturlar, ön çatlatma için polilinyalar, ikincil atım ve blok patlatma için noktalar. Aynı seriye ait atımlar tek bir çevrede birleşir ve sonuç PDF planı, DXF veya görüntü olarak çıkar."],
   []),
 ],
 'note': "Tek bir açık ocak işletmesinde, bu işlemlerden kazanılan süre yılda yaklaşık iki yüz saat olarak tahmin edilmektedir. Gerçek kazanımlar sahaya göre değişir.",
 'bouton': 'Daha fazla bilgi',
 'appel': 'Demo talep edin',
},

'zh': {
 'surtitre': '为什么',
 'titre': '为什么选择 BlastClear',
 'chapo': "钻爆团队在疏散警戒范围上投入大量时间，从设计一直到下发。多数人止步于圆形。以下说明圆形能提供什么、做不到什么，以及弹道穹顶改变了什么。",
 'sections': [
  ("圆形警戒范围提供了什么",
   ["以爆区形心为圆心，它是任何疏散方案都必须具备的最低要求，承担三项作用。"],
   ["评估最大抛掷距离下飞石对爆区周边的影响范围。",
    "提醒人员与设备司机，并保护固定或难以转移的设施。",
    "检验爆破参数（单段药量、堵塞长度）对抛掷距离的影响。"]),
  ("它的两处局限源于形状本身",
   ["并非使用方式所致：圆形二者皆无法兼顾。",
    "<b>它忽略地形。</b> 单一半径被用于并不平坦的地形。朝低处偏小，飞石在那里落得更远；朝高处偏大，飞石在那里落得更近。前者是风险，后者则无谓地占用场地。",
    "<b>它忽略爆破方向。</b> 抛掷并非各向均等：起爆顺序赋予其主导方向。固定半径因此把爆区后方当作前方处理，并处处取最大抛距。"],
   []),
  ("多次爆破，一张图纸",
   ["当相邻的多次爆破安排在同一轮次时，难度随之上升。需要逐个计算警戒范围，将其合并为单一轮廓，而这一切还要基于来自多个软件的文件才能得到图纸。",
    "每一步手工操作都是出错的机会，而这项数据决定着是否要把人员撤离。"],
   []),
  ("弹道穹顶改变了什么",
   ["它同时回应两处局限，并带来四点。"],
   ["<b>它建立在爆区的真实几何形状之上。</b> 由轮廓最外侧的炮孔确定，而不仅是形心。",
    "<b>它与现场地形求交。</b> 所得警戒范围贴合地面、台阶与坡度转折，而非理论水平面。",
    "<b>它按扇区分级。</b> 每个扇区按爆破方向取各自的半径，而不是处处使用同一半径。",
    "<b>它使结果可复现。</b> 相同数据与相同设置得出相同的警戒范围，无论由谁计算。"]),
  ("BlastClear 如何落地",
   ["BlastClear 在同一环境中把这一方法应用于三类爆破：生产爆破的闭合轮廓、预裂爆破的多段线、二次爆破与大块爆破的点位。同一轮次的爆破合并为单一警戒范围，成果可输出为 PDF 图纸、DXF 或图像。"],
   []),
 ],
 'note': "在一处露天矿，此类操作节省的时间估算约为每年两百小时。实际收益视现场情况而定。",
 'bouton': '了解更多',
 'appel': '预约演示',
},

}
